server:
  port: 8083
spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:3306/${MYSQL_DATABASE}?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
      
spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect